apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark

resources:
  - ../../base

patches:
  - path: patch-worker-replicas.yaml
  - path: patch-resources.yaml
  - path: patch-ingress-host.yaml
