apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
  namespace: spark
  labels:
    app.kubernetes.io/name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: airflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: airflow
    spec:
      serviceAccountName: spark-sa

      securityContext:
        fsGroup: 50000

      containers:
        - name: airflow
          image: apache/airflow:2.10.5-python3.11

          imagePullPolicy: IfNotPresent

          command:
            - /bin/bash
            - -c
            - |
              pip install pyspark && \
              airflow standalone

          env:
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: "false"

            - name: AIRFLOW__WEBSERVER__EXPOSE_CONFIG
              value: "true"

            - name: AIRFLOW_UID
              value: "50000"

          ports:
            - containerPort: 8080
              name: airflow-ui

          volumeMounts:
            - name: airflow-logs
              mountPath: /opt/airflow/logs

            - name: spark-events
              mountPath: /opt/spark/spark-events

          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi

      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc

        - name: spark-events
          persistentVolumeClaim:
            claimName: spark-events-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: spark
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: airflow
  ports:
    - name: airflow-ui
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ui
  namespace: spark
spec:
  ingressClassName: public
  rules:
    - host: airflow.tree.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow
                port:
                  number: 8080
