apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - pvc.yaml
  - spark-master.yaml
  - spark-worker.yaml
  - spark-history.yaml
  - services.yaml
  - ingress.yaml
  - networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: spark-standalone
  app.kubernetes.io/managed-by: argocd
