apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-events-pvc
  namespace: spark
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 20Gi
