apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark
  labels:
    app.kubernetes.io/name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-master
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-master
    spec:
      serviceAccountName: spark-sa
      securityContext:
        runAsUser: 185
        runAsGroup: 185
        fsGroup: 185
      containers:
        - name: spark-master
          image: apache/spark:4.0.2
          imagePullPolicy: IfNotPresent
          command:
            - /opt/spark/bin/spark-class
            - org.apache.spark.deploy.master.Master
          envFrom:
            - configMapRef:
                name: spark-config
          env:
            - name: SPARK_LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: master-rpc
              containerPort: 7077
            - name: master-ui
              containerPort: 8080
          volumeMounts:
            - name: spark-events
              mountPath: /opt/spark/spark-events
          readinessProbe:
            tcpSocket:
              port: 7077
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7077
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: spark-events
          persistentVolumeClaim:
            claimName: spark-events-pvc
